"""init

Revision ID: b9728daf0b07
Revises:
Create Date: 2024-06-21 01:15:44.549492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9728daf0b07'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('anime_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('anime_id', name=op.f('pk__anime'))
    )
    op.create_table('watchtime',
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('episode', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.anime_id'], name=op.f('fk__watchtime__anime_id__anime')),
    sa.PrimaryKeyConstraint('anime_id', 'episode', 'season', name=op.f('pk__watchtime'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchtime')
    op.drop_table('anime')
    # ### end Alembic commands ###